---
permalink: adonis-blog-part3
categories:
- tutorial
---
= 数据库模型

toc::[]

到目前为止，我们已经创建了一个新的AdonisJs应用并为它创建了路由，控制器和渲染的视图。本教程，我们将进一步学习  *Database Models* 。

AdonisJs 支持大多数的sql数据库。这是完整的例子 link:database-setup[数据库安装] 。我们将首先创建迁移和数据模型，这些模型也称为Lucid模型。
 

== 什么是数据库模型？
每个数据库模型表示数据库中的单个SQL表。 例如：

[options="header"]
|====
| Model | Database Table
| User | users
| Post | posts
| Category | categories
|====

希望是有道理的。Now to interact with posts, 我们需要两件事情。

[pretty-list]
1. 一个帖子的模型。
2. 和一个帖子数据库表。

== 创建数据库模型
模型是放在一个名为 *app/Model* 的专用目录中。让我们用ace来创建Post模型

[source, bash]
----
./ace make:model Post
----

.输出
[source]
----
create: app/Model/Post.js
----

.app/Model/Post.js
[source, javascript]
----
'use strict'

const Lucid = use('Lucid')

class Post extends Lucid {
}

module.exports = Post
----

每一个模型都是一个专门的 *ES2015 Class* 就像我们的链接 link:controllers[控制器]一样，但每一个模型
都继承Lucid，使得它与普通类不同。

在大多数情况下，你不必触及你的模型。所以我们将保留这个文件，并切换到另一个任务。

== 什么是迁移?
我们的下一步是选择一个我们要使用的数据库，并创建必要的数据库表。 为了简单起见，我们将坚持 *SQLite*。 但是，您可以自由使用 *MYSQL* 或 *PostgreSQL*。

迁移是使用Javascript代码创建数据库表的过程。与使用SequelPro，Workbench等创建数据库表的标准工作流相比迁移具有很多好处。请查看以下链接：link:migrations[Migrations] 指南，以了解有关它们的更多信息。

== 创建迁移
一如往常 *ace (我们的好朋友)* 将为我们创造一个迁移。

[source, bash]
----
./ace make:migration posts --create=posts
----

.输出
[source]
----
create: database/migrations/1464075245386_posts.js
----

快速打开此文件，并探索创建数据库表的选项，而不通过SQL界面来操作。

.database/migrations/1464075245386_posts.js
[source, javascript]
----
'use strict'

const Schema = use('Schema')

class PostSchema extends Schema {

  up () {
    this.create('posts', (table) => {
      table.increments()
      table.string('title')
      table.text('content')
      table.timestamps()
    })
  }

  down () {
    this.drop('posts')
  }

}

module.exports = PostSchema
----

哇！ 在标准Js文件中定义数据库表非常简单。 在处理迁移时，请注意以下几点

[pretty-list]
1. `up` 方法用于创建一个表，或者添加新的字段到现有的表等。
2. `down` 方法总是相反的，当你想要撤销刚才所做的更改时，将可以使用它，也称之为 *回滚*

== SQLite 驱动 & 运行 Migrations
最后，我们需要运行此migration来执行sql创建 *posts* 的数据库，在此之前，我们需要确保SQLlite是正确安装。

.安装 SQLite3 驱动
[source, bash]
----
npm i --save sqlite3
----

.运行 Migrations
[source, bash]
----
./ace migration:run
----

.输出
[source]
----
✔ Database migrated successfully.
----

我们在本教程中涵盖了很多，特别是哪些你觉得是新的概念。这是关于框架的事情，你需要花几天时间才能掌握现有的工具和选项，使你的开发周期在未来容易得多。