---
permalink: directory-structure
categories:
- getting-started
---
= Directory Structure

toc::[]

目录结构首先可能会让你感到压倒一切，因为有一些预配置的目录。慢慢地，您会了解将逻辑实体划分为多个目录的好处，因为它可以保持代码的易维护性维护并易于查找。


[source, bash]
----
├── app
│   ├── Commands
│   ├── Http
│   ├── Listeners
│   ├── Model
├── bootstrap
├── config
├── database
│   ├── migrations
│   └── seeds
├── providers
├── public
├── resources
│   └── views
├── storage
----

== app（应用程序）目录

NOTE: 
请确保了解有关link:dependency-injection[依赖注入] and link:ioc-container[Ioc Container]的更多信息，以了解自动加载的概念。

该`app`目录是您的代码的家，并在命名空间下自动加载App。如果你打开package.json文件，你会发现下面的代码片段。

[source, json]
----
{
  "autoload": {
    "App": "./app"
  }
}
----

您可以自由地将命名空间从`App`更改为任何您想要的。当然，使用默认的命名空间，其他人更容易理解您写的代码。

此外，该`app`目录具有用于不同目的的嵌套目录。目录下的所有子目录首字母都大写，因为AdonisJs遵循命名空间的原则。不幸的是，Javascript或者Node.js没有关于命名空间的约定，所以我们借鉴了其他编程语言（如PHP）的标准/最佳实践。

[options="header"]
|====
| 目录 | 目的
| Commands | 该目录专用于存储`Ace`命令。理想情况下，单个文件代表一个单独的命令。
| Http | 如名称所示，Http目录专用于与HTTP服务器相关的实体，如：*控制器*，*中间件*和*路由*。
| Listeners | Listeners目录可以更容易地组织您的事件监听器，因为事件的内联关闭是不可维护的，也不可测试。你可以自由地为此目录中的*Redis Pub/Sub*创建侦听器。
| Model | 模型目录有您的Lucid模型。此外，该目录中还有一个*Hooks*目录来存储模型钩子。
|====

== bootstrap（引导）目录

该`bootstrap`目录是加入您的应用程序的HTTP服务器和ace命令，在这个目录中需要使用几个文件。

[options="header"]
|====
| 文件 | 作用
| app.js | 此文件用于注册服务提供商/命令，并为常用命名空间设置别名。
| events.js | 您可以使用此文件来注册特定事件的侦听器。像Listeners目录一样，您也可以使用此文件注册*Redis Pub/Sub*的侦听器。
| extend.js | 此文件用于扩展核心/第三方服务提供商。
|====

TIP: 为了使未来的升级变得简单易用，建议您不要修`改bootstrap/http.js`和`bootstrap/kernel.js`文件。

== config（配置）目录
该`config`目录用于定义应用程序的配置。AdonisJs本身带有一堆配置文件，但您也可以自由创建配置文件。

为了可以在任意文件中读取配置文件的设置，你应该使用`Config`provider,在你的代码中不需要手动引入文件，下面是示例

.Wrong
[source, javascript]
----
const app = require('./config/app.js')
console.log(app.appKey)
----

.Right
[source, javascript]
----
const Config = use('Config')
console.log(Config.get('app.appKey'))
----

== database（数据库）目录
所有与数据库相关的文件都存储在database目录中，由于SQLite是一个基于文件的数据库，SQLite文件也将存储在这个目录中。

[options="header"]
|====
| 目录/文件 | 目的
| migrations | 此目录具有使用该`make:migration`命令创建的所有迁移。了解更多关于迁移link:migrations[这里].
| seeds | 用于使用虚拟数据预填充数据库。它们有助于设置应用程序的初始状态。
| factory.js | 工厂用于生成Lucid模型或数据库表的假数据。你在写测试时会发现自己在工厂里使用很多。`factory.js`是您为虚拟数据定义蓝图的地方。
|====

== providers（providers）目录
如果您觉得需要编写您的providers，这是保留他们的地方，建议在*npm*上发布可重复使用的providers。

理想情况下，没有创建提供商的严格规则，只需确保阅读服务提供商文档，了解如何构建提供程序。内部服务供应商`providers`目录中通过定义内的绝对路径注册`app.js`文件。

[source, javascript]
.bootstrap/app.js
----
const path = require('path')

const providers = [
  path.join(__dirname, '../providers/MyAwesomeProvider')
]
----

== public（公共）目录
顾名思义，该public目录用于通过HTTP提供静态资源。从路径`/public`中引用文件时，不需要写`/public`。例如：

.public/style.css
[source, html]
----
<link rel="stylesheet" href="/style.css" />
----

== resources（资源）目录
该`resources`目录用于存储应用程序的演示文件。Nunjucks `视图`也存储在此目录中，您可以自由创建用于存储*Sass*/*Less*或任何前端构建相关文件的其他目录。

[options="header"]
|====
| 目录 | 目的
| views | Nunjucks视图存储在此目录中，views已创建了*partials* or *layouts*。
|====

== storage（存储）目录
应用程序日志和会话存储在`storage`目录中。将其视为应用程序的临时存储。此外，该目录被添加到.gitignore，以便您的开发相关日志/会话不会提交给版本控制提供程序，如Github或Bitbucket。
