---
permalink: routing
categories:
- getting-started
---
= 路由

toc::[]

HTTP 路由器向所有的网站浏览的用户提供了一个可以访问你的网站的链接(URL), AdonisJs 路由通过绑定Url和网站后台功能, 让用户可以访问某个链接来执行对应的操作.

所有的路由都保存在 `app/Http/routes.js` 文件里面, 他们都会在HTTP服务器启动的时候自动载入.

NOTE: 所有本文档的小例子, 都使用 `闭包 (Closures)` 的方式定义一个路由的动词, 但是依然推荐创建 *控制器(Controllers)* 来管理你的路由, 这样你就可以让你的路由文件变得简洁, 方便测试.

video::w7LD7E53w3w[youtube, width=100%, height=480]

== 小例子
.app/Http/routes.js
[source, javascript]
----
const Route = use('Route')

Route.get('/', function * (request, response) {
  response.send('这是我的网站首页~')
})
----

在上面的例子中, 我们为根链接 *URL(/)* 创建了一个路由, 并且绑定上了一个闭包, 这里有几件关于闭包的几件事:

[pretty-list]
1. 闭包是一个 ES2015 规范下的生成器, 也就是说, 你可以用yield关键字来执行异步操作. 你可以看看Strongloop写的关于生成器的link:https://strongloop.com/strongblog/write-your-own-co-using-es2015-generators/[文章, window="_blank"]
2. AdonisJs 使用了全称 `request` 和 `response`, 而不是缩写 `req` 和 `res`.

==== 中间件(...中间件)
为一个路由定义一个中间件

.app/Http/routes.js
[source, javascript]
----
Route.get('/authenticated', function * (request, response) {
  response.send('你的访问已被授权~')
}).middleware('auth')
----

也可以添加多个中间件

.app/Http/routes.js
[source, javascript]
----
Route.get('/secured', function * (request, response) {
  response.send('你的访问已被授权~')
}).middleware(['auth', 'custom'])
----

== HTTP 动词(verbs)
HTTP动词也被称为HTTP方法, 最简单的例子就是, 我们用POST安全地去提交一个表单.

HTTP动词不仅仅有`GET`和`POST`, 这里有很多有用的其他方法在AdonisJs里面可以使用

[options="header"]
|====
| 动词 | 路由方法
| GET | Route.get
| POST | Route.post
| PUT | Route.put
| PATCH | Route.patch
| DELETE | Route.delete
|====

如果你想用自定义的HTTP动词/方法, 你可以使用`route`来定义他们.

==== route(url, verbs, action)
[source, javascript]
----
const Route = use('Route')

Route.route('/', 'COPY', function * (request, response) {
})

// MULTIPLE VERBS

Route.route('/', ['COPY', 'MOVE'], function * (request, response) {
})
----

== 单页面网页程序(SPA)的路由
在单页面网页程序的路由通常被前端JS框架(Angular, Vue, React)接手管理了, 所以通常你的大部分操作都是用API来实现的, AdonisJs也为此提供了非常方便的解决方案.

==== any(url, action)
[source, javascript]
----
Route.any('*', function * (request, response) {
  yield response.sendView('home')
})
----

这个小例子里的`any`方法将会绑定所有的路由动词到这个链接, 而'*'这个匹配符, 让你的所有链接都可以访问这个路由. (译者: 其实这个例子很差)

最后, 这个路由会返回一个只有简单HTML代码的`页面内容(view)`.

== 路由参数
路由参数让你的路由可以动态的匹配一个链接(URL), 这样你就可以动态的接受一些参数, 看看这个小例子

[source, javascript]
----
Route.get('users/:id', function * (request, response) {
  const id = request.param('id')
  response.send(`耶, 我得到了一个动态ID: ${id}`)
})
----

在这个小例子中, `:id`就是一个动态的参数, 像`/user/1` 或 `/user/20`这样的链接将会被匹配上.

你可以把这个动态参数设置为可选的(可有可无).

[source, javascript]
----
Route.get('make/:drink?', function * (request, response) {
  const drink = request.param('drink', 'coffee')
  response.send(` ${drink} 如果没有被传入, 我会得到coffee这个字段哦~`)
})
----

`?` 让`/make`或`/make/shake`链接都匹配上~

也许你想匹配任意个数的参数, 你可以用`*`, 这样你就可以模拟访问一个文件啦~, 比如:`/~/media/xyz.pdf`, 看看下面这个小例子:

[source, javascript]
----
Route.get('/~/*', function * (request, response) {
  const media = request.param(0)
  response.send(`哟~ 这个${media}文件, 不给你哦~`)
})
----

[NOTE]
====
这个小例子里面, 你任然可以使用`*`
[source, javascript]
----
// 链接: `/~/media/xyz.pdf?download`
Route.get('/~/*', function * (request, response) {
  const media = request.param(0)

  if (request.input('download') !== null) {
    // ...
  }

  response.send(`哎~ 这个${media}文件, 送你了~`)
})
----
====


== 路由内容协商
link:https://en.wikipedia.org/wiki/Content_negotiation[(内容协商)Content negotiation, window="_blank"] 让你找到一个合适的方法返回数据.一般来说, HTTP表头*Accept*字段就是用来告诉服务器想要的内容类型, 但是一些现代的Apps通过定义后缀名来清楚的要求它们想要的文件类型.

一个`/users.json`链接将会返回一个JSON结果, 也就是说访问`/users.html`你将会得到一个html页面.

AdonisJs让可以在定义路由方法的同时定义返回类型.

==== formats(types, [strict=false])
[source, javascript]
----
Route
  .get('users', function * (request, response) {
    const format = request.format() <1>
  })
  .formats(['json', 'html'])
----

<1> 链接`/users.json`将会返回`json`结果, `/users.html`将会放回一个html结果. 与此同时, `/users`也会工作, 不过, 这时候的类型就是未定义的(undefined), 如果你想强制访问`json`或`html`类型, 可以设置`strict`为true.

== 路由渲染
每个网站都有一些静态的HTML页面, 之所以称之为静态, 是因为这些页面都是没有任何逻辑和数据库里数据, 小例子:

1. 关于我们的页面
2. 联系我们的页面

我们就从这个简单的例子入手, 来渲染一个关于我们页面

.不太好的例子
[source, javascript]
----
Route.get('about', function * (request, response) {
  yield response.sendView('about')
})
----

上面这个例子, 我们注册了一个路由, 传入了一个闭包, 然后渲染了一个页面, 之所以不优秀是因为它占用了我们3排代码空间~


AdonisJs路由层提供了一个简化方法, 使用`on`和`render`

.优秀的例子
[source, javascript]
----
Route.on('about').render('about')
----

这仅仅是一个很小的功能, 但省下了很多的代码空间和时间, 而且看上去很简单.

TIP: *BONUS*: 通过render函数渲染的html模板是使用了 link:/request[request] 对象.

== 路由组
路由分组在你需要给多个路由定义相同属性的时候特别有用, 这样你就不用重复的定义这些属性了. 举个例子, 给多个路由添加链接前缀`(api/v1)`.

==== group(uniqueName, callback)
[source, javascript]
----
Route.group('version1', function () {
  Route.get('users', function * (request, response) {
    // ...
  })
}).prefix('api/v1')
----

所有路由在以上分组里面都会被添加上`/api/v1`前缀, 也就是说通过访问`/api/v1/users`才可以访问到小例子中定义的`/users`

路由组不仅可以添加前缀, 还可以添加很多东西~

==== 中间件(...中间件)
为路由组里面的所有路由添加中间件

[source, javascript]
----
Route.group('authenticated', function () {
  // ...
}).middleware('auth')
----

==== 域名(子域名)
为一个路由组定义一个属于它们自己的子域名.

[source, javascript]
----
Route.group('my-group', function () {
  Route.get('posts', function * (request, response) {
    // ...
  })
}).domain('blog.mydomain.dev')
----

只有访问`blog.mydomain.dev/posts` 才会调用定义的`/posts`路由.

==== 类型(formats, [strict=false])
你可以给路由组添加内容协商

== 命名路由
路由都定义在`app/Http/routes.js`文件里, 但是你可以在任何地方使用.


1. 在html里面, 你想创建一个导航栏
2. 在一个控制器里面你想跳转到另外一个链接.

当你的网站越来越大, 你可能会频繁的修改链接与路由的对应, 这时候你到处去修改html对应的链接, 你肯定要爆炸了.

这是个给路由取个名字, 就算路由对应链接改了, 你也能轻松找到到这个新的链接.

==== as(name)
[source, javascript]
----
Route
  .get('users/:id', 'UserController.show')
  .as('profile')
----


这时候, 你可以调用linkTo这个帮助函数, 来帮你找到对应链接.

[source, twig]
----
{{ linkTo('profile', 'View Profile', { id: 1 }) }}
{{ linkTo('profile', 'View Profile', { id: 1 } , '_blank') }}
----

.生成代码
[source, html]
----
<a href="/users/1"> View Profile </a>
<a href="/users/1" target="_blank"> View Profile </a>
----

`linkTo`函数只会为你生成一个包含链接的a标签, 而你可以用`route`这个模板过滤器来帮助你生成一个链接.

[source, twig]
----
<form action="{{ 'profile' | route({id: 1}) }}" method="POST"></form>
----

.输出
[source, html]
----
<form action="/user/1" method="POST"></form>
----

== 资源路由
路由层让你更快的定义一个增删改查(CURD)操作的路由, 你就不用自己手动定义很多路由了.

==== resource(name, controller)
[source, javascript]
----
const Route = use('Route')
Route.resource('users', 'UserController')
----

.Output
[options="header"]
|====
| 链接 | 动词 | 控制器里面对应方法 | 目的
| /users | GET | UserController.index | Show list of all users
| /users/create | GET | UserController.create | Display a form to create a new user.
| /users | POST | UserController.store | Save user submitted via form to the database.
| /users/:id | GET | UserController.show | Display user details using the id
| /users/:id/edit | GET | UserController.edit | Display the form to edit the user.
| /users/:id | PUT/PATCH | UserController.update | Update details for a given user with id.
| /users/:id | DELETE | UserController.destroy | Delete a given user with id.
|====

这里有几个注意事项

1. 你永远都要记得给资源路由注册一个控制器
2. AdonisJs将会自动给每个路由自动绑定上对应的方法, 你不能自定义.

=== 嵌套资源路由
资源路由可以使用`.`符号来定义嵌套资源路由

[source, javascript]
----
Route.resource('posts.comments', 'CommentsController')
----

=== 过滤路由
`资源路由`会创建7个路由. 可能有些你用不到, 所以AdonisJs给你了一个方法来去除他们.

==== except(...actions)
`except`将会去除你提供的方法
[source, javascript]
----
Route
  .resource('users', 'UserController')
  .except('create', 'edit')
----

==== only(...actions)
`only` 与 xref:_except_actions[except] 恰恰相反.

[source, javascript]
----
Route
  .resource('users', 'UserController')
  .only('index', 'store', 'show', 'update', 'delete')
----

=== 扩展资源路由
如果你想扩展资源路由, 你需要添加自定义的路由和控制器方法, 给你讲几个非常实用例子来解释:

1. `authors`(作家)路由可以被扩展一个新的路由来展示受欢迎的作家(popular authors)
2. `posts`(文章)路由可以添加几个路由来添加或展示文章的评论, 当然你也可以给文章评论分配一个单独资源路由.

==== addCollection(route, [verbs=GET], [callback])
`addCollection`方法就可以让你给当前资源路由添加一个新的路由, 默认使用的是*GET*动词, 在控制器的方法名和你设置路由名一样(下面小例子为例就是popular).

[source, javascript]
----
Route
  .resource('authors', 'AuthorsController')
  .addCollection('popular')
----

.输出
[options="header"]
|====
| Url | Verb | Controller Method | Purpose
| /authors/popular | GET | AuthorsController.popular | List popular authors
|====

当然, 你可以添加一个不同动词的路由, 并让它对应一个你想要的控制器的方法.

[source, javascript]
----
Route
  .resource('authors', 'AuthorsController')
  .addCollection('popular', ['GET', 'HEAD'], (collection) => {
    collection.bindAction('popularAuthors')
  })
----

==== addMember(route, [verbs=GET], [callback])
这个方法和 xref:_addcollection_route_verbs_get_callback[addCollection] 写法一样, 不过它为资源路由的每一个的结果添加了一个路由.

[source, javascript]
----
Route
  .resource('posts', 'PostsController')
  .addMember('comments')
----

.输出
[options="header"]
|====
| 路由 | 动词 | 控制器方法 | 目的
| /posts/:id/comments | GET | PostsController.comments | List comments for a given post
|====

你可以注意到, `comments` (评论)路由, 添加在了每一个具体的文章上, 你也可以定义一个xref:_middleware_middleware[中间件]和xref:_as_name[命名]来扩展路由.

[source, javascript]
----
Route
  .resource('posts', 'PostsController')
  .addMember('comments', ['GET'], (member) => {
    member.middleware('auth').as('postsMember')
  })
----

TIP: 中间件可以添加在一整个资源路由上`Route.resource().middleware()`
