---
permalink: middleware
categories:
- getting-started
---
= 中间件

toc::[]

HTTP中间件在你的路由执行操作前执行, 这个东西非常常见, 你可以看看这个小例子.

*请求主体解析器(body parser)*中间件的作用是解析请求主体内容, *授权(Auth)*中间件是一个登陆中间件, 如果用户没有登陆就会抛出*401异常*.

中间件可以做到:

[pretty-list]
1. 修改请求对象, 比如在里面添加数据.
2. 在没有执行你的路由操作的情况下, 直接给用户一个HTTP响应.
3. 拒绝一个请求, 并返回一个HTTP错误.

== 全局中间件
全局中间件需要在`app/Http/kernel.js`文件里面定义(数组方式), 定义之后, 这个中间件在执行路由操作前都会被执行.

.app/Http/kernel.js
[source, javascript]
----
const globalMiddleware = [
  // ...
  'Adonis/Middleware/Cors',
  'Adonis/Src/BodyParser',
  // ...
]
----

== 命名中间件
命名中间件是一个拥有独立名字的中间件, 每当你需要用它, 你就得手动的添加这个中间件, 比如`Auth`中间件就是阻止未登录/未授权用户访问路由的中间件.

.app/Http/kernel.js
[source, javascript]
----
const namedMiddleware = {
  // ...
  auth: 'Adonis/Middleware/Auth'
  // ...
}
----

.使用方法

[source, javascript]
----
Route
  .get('accounts/:id', 'AccountsController.show')
  .middleware('auth')

// or

Route.group('auth-routes', () => {
  Route.get('accounts/:id', 'AccountsController.show')
}).middleware('auth')
----

== 新建一个自己的中间件
中间件的所在目录是`app/Http/Middleware`. 每个中间件都要求必须是一个ES2015规范的类, 并且必须要有一个handle方法.

让我们来用ace工具创建一个中间件.

[source, bash]
----
./ace make:middleware CountryDetector

# 创建了: app/Http/Middleware/CountryDetector.js
----

.app/Http/Middleware/CountryDetector.js
[source, javascript]
----
'use strict'

class CountryDetector {

  * handle (request, response, next) {
    yield next
  }

}
----

[pretty-list]
1. `handle`方法是一个ES2015规范的生成器(generator).
2. 在你的controller方法里面, 你会得到link:request[request], link:response[response]和一个`next`传入参数.
3. 如果你想继续调用下一个中间件或者是路由方法(一般都需要, 除非你想终止这次访问), 记得调用`yield next`.
4. 还有, 你可以通过response类实例终止这次方法.

现在, 我们来创建一个*CountryDetector*中间件, 这个中间件根据ip判断用户所在国家.

.app/Http/Middleware/CountryDetector.js
[source, javascript]
----
'use strict'

const geoip = use('geoip-lite') // npm module

class CountryDetector {

  * handle (request, response, next) {
    const ip = request.ip()
    request.country = geoip.lookup(ip).country
    yield next
  }

}
----

接下来, 我们需要注册这个中间件, 注册成全局中间件还是命名中间件就需要看你自己的需求了. 我们现在举个注册成全局中间件的例子.

.app/Http/kernel.js
[source, javascript]
----
const globalMiddleware = [
  // ...
  'App/Http/Middleware/CountryDetector'
  // ...
]
----

恭喜~请求类对象都有了一个`country`的属性, 你可以用`request.country`来访问.
