---
permalink: files
categories:
- getting-started
---
= 文件

toc::[]

AdonisJs有内置直接处理文件上传的功能, 你可以很轻松的管理批量上传, *文件大小和文件类型插件(file size/extension validation)* 可以限制用户上传文件大小.

== 小例子

以上传用户头像为例, 我们用**PUT**方法来上传文件, 并且做一个文件有效检测.

.app/Http/routes.js
[source, javascript]
----
Route.put('/users/:id/avatar', 'UsersController.updateAvatar')
----

接下来, 你需要在`UsersController`里面创建`updateAvatar`方法.

.app/Http/Controllers/UsersController.js
[source, javascript]
----
'use strict'

const Helpers = use('Helpers')
const User = use('App/Model/User')

class UserController {

  * updateAvatar (request, response) {

    const avatar = request.file('avatar', { <1>
      maxSize: '2mb',
      allowedExtensions: ['jpg', 'png', 'jpeg']
    })

    const userId = request.param('id')
    const user = yield User.findOrFail(userId)

    const fileName = `${new Date().getTime()}.${avatar.extension()}` <2>
    yield avatar.move(Helpers.storagePath(), fileName) <3>

    if (!avatar.moved()) {
      response.badRequest(avatar.errors())
      return
    }

    user.avatar = avatar.uploadPath() <4>
    yield user.save()
    response.ok('Avatar updated successfully')
  }
}
module.exports = UsersController
----

<1> 首先我们从`request`对象上获得文件. 同时我们可以定义`maxSize`和`allowedExtensions`去验证文件是否符合标准.
<2> 重命名很重要, 比如获得当前时间加上后缀名作为新的文件名.
<3> 接下来, 我们调用move函数来移动文件, 任何的文件验证错误, 都可以从`error()`函数获得.
<4> 如果代码都执行成功, 我们可以直接把文件路径放到数据库模型里面, 这样就可以存到数据库里面了.

== 配置

上传文件配置在`config/bodyParser.js`里面.

.config/bodyParser.js
[source, javascript]
----
uploads: {
  multiple: true,
  hash: false,
  maxSize: '2mb'
}
----

1. `最大文件大小(maxSize)`是计算的所有的上传文件, 两个1.5MB的文件就会不满足2MB上传大小.
2. `最大文件大小(maxSize)`将会上传前验证, 这样就防止恶意攻击上传非常大的垃圾文件.

== 文件实例

`request.file`方法返回一个`File`类, 有很多的方法来获取文件的信息以及移动文件.

上传多个文件之后, 你会获得一个包含多个`File`的数组. 小例子:

[source, javascript]
----
const profilePics = request.file('profile[]')
// profilePics will be an array
----

== 验证

**文件实例**可以验证你的文件大小和后缀名, 传入两个可选项即可.

[source, javascript]
----
const avatar = request.file('avatar', {
  maxSize: '2mb',
  allowedExtensions: ['jpg', 'png']
})
----

当你调用`move`方法时, 就会开始验证, 如果这两个验证不满足你的需求, 你可以自定义你自己的验证.

=== 手动验证
Returning *true* or *false* from the `validate` method will define whether the validation has been passed or not. Also, you will be responsible for setting the error message on the file instance manually.
返回*true*就会通过验证. 返回*false*就不能通过, 记得你需要自己设置错误信息.

[source, javascript]
----
const avatar = request.file('avatar')

avatar.validate = function () {
  if (avatar.extension() !== 'foo') {
    avatar._setError('We support foo files only')
    return false
  }
  return true
}
----

== 文件实例方法
下面就是一些内置的文件实例方法.

==== clientName
返回上传文件名.

[source, javascript]
----
avatar.clientName()
----

==== clientSize
返回文件大小(bytes).

[source, javascript]
----
avatar.clientSize()
----

==== mimeType
返回mine-type.

[source, javascript]
----
avatar.mimeType()
----

==== extension
返回文件后缀名.

[source, javascript]
----
avatar.extension()
----

==== tmpPath
返回上传文件所在的临时路径.

[source, javascript]
----
avatar.tmpPath()
----

==== exists
判断文件是否存在于临时路径.

[source, javascript]
----
avatar.exists()
----

==== move(toPath, [newName])
移动文件到目标路径, 如果`新名字(newName)`没有设置, 将会采用原始的文件名.

[source, javascript]
----
yield avatar.move(Helpers.storagePath())
----

==== delete()
在移动文件之后, 从临时目录里面删除这个文件.

[source, javascript]
----
yield avatar.delete()
----

==== moved
判断文件是否移动成功.

[source, javascript]
----
yield avatar.move(Helpers.storagePath())

if (avatar.moved()) {
    // moved successfully
}
----

==== errors
返回移动文件时出现的错误.

[source, javascript]
----
yield avatar.move(Helpers.storagePath())

if (!avatar.moved()) {
  response.send(avatar.errors())
}
----

==== uploadPath

返回上传文件当前路径.

[source, javascript]
----
yield avatar.move(Helpers.storagePath())

avatar.uploadPath()
----

==== uploadName

上传文件的当前名称.

[source, javascript]
----
yield avatar.move(Helpers.storagePath(), 'selfie.jpg')
avatar.uploadName()
----

NOTE:: `uploadPath` 和 `uploadName` 在移动文件后才能调用.

==== toJSON

以**JSON**形式返回文件属性.

[source, javascript]
----
avatar.toJSON()
----
