---
permalink: contributing
categories:
- prologue
---
= Contribution Guide

toc::[]

所有开放源码项目都由一个充满活力的社区*的用户和协作者进行维护和支持。我们鼓励您通过贡献源代码，改进文档或报告潜在错误，积极参与AdonisJs的开发和未来。

== 渠道

1. link:https://github.com/adonisjs[Github 代码库, window="_blank"] - 在AdonisJs的代码库中报告错误。尝试提供确切的问题和要求来帮助我们重现这个问题。
2. link:https://gitter.im/adonisjs/adonis-framework[Gitter, window="_blank"] - 在这里提出问题或与我们讨论共同的话题。随时加入并分享您的意见。
3. link:https://trello.com/b/yzpqCgdl/adonis-for-humans[Trello, window="_blank"] - AdonisJs的规划Roadmap。包含我们尝试更新与即将进入AdonisJs的计划和功能。
4. link:https://twitter.com/adonisframework[Twitter, window="_blank"] - 关注官方Twitter帐户。随时随地了解我们每天的进度。

== 报告错误

在提交问题时始终尝试提供详尽的描述。您应该提供足够的上下文和信息来重现问题。

1. 分享您所在框架的版本。 AdonisJs是几个子模块的组合，您可以在项目“package.json”文件中找到这些子模块的版本。
2. 分享一个代码段，而不是说“XXX”不起作用。
3. 如果您可以使用示例代码库帮助我们重现问题就更好了。

== 编码风格

JavaScript有几个linters来保持编码风格的一致性。我们利用 link:http://standardjs.com[JavaScript Standard Style, window="_blank"]，这是一个不可配置的模块，使其更容易保持一致的代码风格。

Each module of AdonisJs installs the *Standard Style Linter* as a development dependency. So before submitting your PR make sure to lint your code.
AdonisJs的每个模块安装*Standard Style Linter*作为开发依赖。所以在提交你的PR之前，请确保lint你的代码。

[source, bash]
----
npm run lint
----

== Sharing PR's & Git Flow
== 分享 PR's & Git Flow

我们利用 https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow[Git Flow] 来处理新功能和管理版本。

Below are the rules we follow every day.

[pretty-list]
1. When you start working, think of a feature or problem you are trying to fix.
2. Fork the repository.
3. Create a new feature branch from *develop branch*.
4. Work on it until you feel comfortable to create a pull request.
5. End this feature and push to your forked repository
6. Create a pull request of your feature to AdonisJs repository *develop branch*.
7. If all is good, we will merge the changes and thank you for your contribution.

== Commitizen

We make use of link:https://commitizen.github.io/cz-cli[Commitizen, window="_blank"] to follow naming conventions for commit messages.
