---
permalink: database-setup
categories:
- database
---
= 数据库设置

toc::[]

AdonisJs具有开箱即用的SQL数据库，并提供统一的Javascript API与数据库进行交互。以下是支持的数据库的列表。

== 支持的数据库
[support-list]
* PostgreSQL
* SQLite
* MySQL
* MariaDB
* Oracle
* MSSQL

== 配置
每个AdonisJs应用程序附带预先配置link:query-build[查询构建器]和link:lucid[易懂的Orm]您只需要根据需要调整配置。

默认情况下，配置将使用SQLite作为正在开发的数据库，可以使用`config / database.js`文件来更改。

.config/database.js
[source, javascript]
----
module.exports = {
  connection: Env.get('DB_CONNECTION', 'sqlite'), <1>

  sqlite: {
    ....
  }, <2>

  mysql: {
    ....
  }
}
----

<1>`connection`属性定义用于进行SQL查询的默认连接。
<2>连接名称旁边设置个人连接配置。您可以自由创建多个配置块

== 基本例子
让我们从“users”表中选择所有用户，开始播放数据库提供者。

.路由
[source, javascript]
----
Route.get('/users', 'UsersController.index')
----

.Controller
[source, javascript]
----
'use strict'

const Database = use('Database')

class UsersController {

  * index (request, response) {
    const users = yield Database.select('*').from('users')
    response.json(users)
  }

}
----

提示：查询构建器语法流畅，这意味着您可以链接方法来构建完整的SQL查询。此外，当您在多个数据库之间切换时，您不必更改一行代码。

== 数据库驱动程序及其设置
由于AdonisJs支持所有流行的SQL数据库，因此您必须从npm安装其等效的驱动程序，并按如下定义进行配置

=== MySQL
可用的驱动程序::
link:https://www.npmjs.com/package/mysql[mysql] +
link:https://www.npmjs.com/package/mysql2[mysql2]

组态::
+

[source, javascript]
----
mysql: {
  client: 'mysql',
  connection: {
    host: '127.0.0.1',
    port: 3306,
    user: 'root',
    password: '',
    database: 'adonis'
  }
}
----

此外，您可以定义一个套接字路径来构建MySQL连接。给出套接字路径会忽略主机和端口选项。

[source, javascript]
----
mysql: {
  client: 'mysql',
  connection: {
    socketPath: '/path/to/socket.sock',
    user: 'root',
    password: '',
    database: 'adonis'
  }
}
----

=== SQLite
可用的驱动程序::
link:https://www.npmjs.com/package/sqlite3[sqlite3]

组态::
+

[source, javascript]
----
sqlite: {
  client: 'sqlite3',
  connection: {
    filename: Helpers.storagePath('development.sqlite')
  }
}
----

=== PostgreSQL
可用的驱动程序::
link:https://www.npmjs.com/package/pg[pg]

组态::
+

[source, javascript]
----
pg: {
  client: 'pg',
  connection: {
    host: '127.0.0.1',
    port: 5432,
    user: '',
    password: '',
    database: 'adonis',
    ssl: false
  }
}
----

此外，您可以传递一个连接字符串

[source, javascript]
----
pg: {
  client: 'pg',
  connection: 'postgres://user:password@host:port/database?ssl=true'
}
----

=== Oracle
可用的驱动程序::
link:https://www.npmjs.com/package/oracle[oracle] +
link:https://www.npmjs.com/package/strong-oracle[strong-oracle]

Configuration::
+

[source, javascript]
----
oracle: {
  client: 'oracle',
  connection: {
    host: '127.0.0.1',
    port: 1521,
    user: '',
    password: '',
    database: 'adonis'
  }
}
----

=== MariaDB

可用的驱动程序::
link:https://www.npmjs.com/package/mariasql[mariasql]

组态::
+

[source, javascript]
----
maria: {
  client: 'mariasql',
  connection: {
    host: '127.0.0.1',
    port: 3306,
    user: 'root',
    password: '',
    database: 'adonis'
  }
}
----

=== MSSQL
可用的驱动程序::
link:https://www.npmjs.com/package/mssql[mssql]

组态::
+

[source, javascript]
----
mssql: {
  client: 'mssql',
  connection: {
    host: '127.0.0.1',
    port: 3306,
    user: 'root',
    password: '',
    database: 'adonis'
  }
}
----

== 调试
调试数据库查询可方便地检查数据库响应时间，或确保查询构建器执行正确的查询。我们来看几个不同的调试策略。

=== 全局
全局调试查询的最简单的方法是在配置块上设置`debug`标志。

.config/database.js
[source, javascript]
----
mysql: {
  client: 'mysql',
  connection: {},
  debug: true <1>
}
----

此外，您可以通过监听数据库提供程序上的“query”或“sql”事件来在代码中调试开关。注册一个监听器的最佳位置是`app / Listeners / Http.js`文件。

.app/Listeners/Http.js
[source, javascript]
----
Http.onStart = function () {
  Database.on('query', console.log)
  Database.on('sql', console.log)
}
----

`query`和`sql`的唯一区别

SQL event output::
+

[source, mysql]
----
+ 1.38 ms : select * from `users` where `username` = 'doe'
----

Query event output::
+

[source, javascript]
----
{
  method: 'select',
  options: {},
  bindings: [ 'doe' ],
  sql: 'select * from `users` where `username` = ?'
}
----

=== Individual Query
Also, you can debug a single query by chaining the event listener when running the query.

[source, javascript]
----
yield Database
  .on('sql', console.log)
  .table('users')
  .where('username', 'doe')
----

Or

[source, javascript]
----
yield Database
  .debug()
  .table('users')
  .where('username', 'doe')
----
