---
permalink: migrations
categories:
- database
---
= 迁移

toc::[]

数据库迁移是一种从代码创建，更改和删除数据库表而不是编写SQL查询的过程。 AdonisJs具有开箱即用的数据库迁移支持功能，可以在应用程序代码库中设置数据库表。

== 介绍

=== Naive方式
数据库管理的*naive*方法是手动创建SQL数据库表这些工作，但它不是优雅的，因为它需要大量的手动重新工作。

我们举一个创建数据库表的标准过程的例子。

1.登录到SequelPro（或类似的）并创建数据库表。
2.现在当有人想要在同一个应用程序上工作时，您需要与它们共享数据库模式或转储。
3.当数据库进行一些更改时，他们必须与您重新共享新的数据库转储。
4.您无法对TravisCI（或类似的）运行自动测试，因为您需要访问服务器才能创建数据库表。
5.最后，在生产中部署应用程序时，需要与服务器数据库进行远程连接以手动创建这些表。

=== 迁移
使用迁移*SQL schema*是您的代码库的一部分，这意味着一旦您的同事将从git客户端检出代码，它们将获得数据库模式，并且可以对其进行任何渐进更改。

== 关于迁移
[pretty-list]
1. 迁移存储在`database / migrations`文件夹中。
2. 每个架构文件都是一个ES2015类，其中有两个必需的方法叫做`up`和`down`。
3. 运行迁移时执行`up`方法。
4. 在迁移回滚期间调用`down`方法。
5. 批处理执行迁移，使您可以灵活地回滚到给定的批处理。

== 基本例子
现在，您了解迁移的好处，让我们进一步了解如何使用Javascript创建SQL数据库表。

[source, bash]
----
./ace make:migration users --create=users
----

.Output
[source, bash]
----
create: database/migrations/1464437815620_users.js
----

.database/migrations/1464437815620_users.js
[source, javascript]
----
'use strict'

const Schema = use('Schema')

class UsersSchema extends Schema {
  up () {
    this.create('users', (table) => {
      table.increments()
      table.timestamps()
    })
  }

  down () {
    this.drop('users')
  }
}

module.exports = UsersSchema
----

== 运行迁移
`migration:run`命令用于执行`database/migrations`目录中存储的所有迁移。 AdonisJs将会巧妙地跳过已经执行的迁移，而不执行新迁移。

[source, bash]
----
./ace migration:run
----

建议使用增量迁移，而不是每次修改相同的schema文件。例如

[pretty-list]
1. 要创建一个新的表时，创建一个新的schema文件。
2. 沿着这条线，你意识到你需要两个额外的字段在同一个表。创建一个新的schema文件来改变现有的表并添加这两个新字段。
3. 再过几天，您需要重命名现有的字段。为此创建一个新的schema文件。

增量迁移可帮助您跟踪版本控制等更改。编写代码时，做一个小的代码提交是一个很好的做法，这样你就可以获得更清晰的代码历史。您必须以相同的方式对待您的迁移。

== 命令列表
以下是仅适用于迁移的ace命令的列表。

[options="header"]
|====
| 命令 | 参数 | 目的
| migration:run | none  | 通过执行所有模式文件的方法来运行所有挂起的迁移。
| migration:rollback | [batch=last] | 将迁移回滚到给定批次或默认为最后一批。
| migration:refresh | none | 通过删除并重新运行所有迁移来刷新迁移。
| migration:reset | none | 回滚到初始状态。
| migration:status | none | 检查当前的迁移状态。
|====

== 与表交互

==== create(tableName, callback)
创建一个新的数据库表。

[source, javascript]
----
class UserSchema {
  up () {
    this.create('users', (table) => {
      ...
    })
  }
}
----

==== createIfNotExists(tableName, callback)
只有表不存在时创建，否则默认忽略*create*命令。

[source, javascript]
----
class UserSchema {
  up () {
    this.createIfNotExists('users', (table) => {
      ...
    })
  }
}
----

==== rename(from, to)
重命名现有的数据库表。

[source, javascript]
----
class UserSchema {
  up () {
    this.rename('users', 'my_users')
  }
}
----

==== drop(tableName)
删除现有的数据库表。

[source, javascript]
----
class UserSchema {
  down () {
    this.drop('users')
  }
}
----

==== dropIfExists(tableName)
只有当数据库表存在时删除，否则默认忽略*drop*命令。

[source, javascript]
----
class UserSchema {
  down () {
    this.dropIfExists('users')
  }
}
----

==== has(tableName)
返回一个*boolean*表示数据库表是否存在。

[source, javascript]
----
class UserSchema {
  up () {
    this.has('users').then((exists) => {
      if (!exists) {
        // do something
      }
    })
  }
}
----

==== table(tableName, callback)
用*alter*选择一个表。

[source, javascript]
----
class UserSchema {
  up () {
    this.table('users', (table) => {
      table.dropColumn('deleted_at')
    })
  }
}
----

==== raw(statement)
在schema构建器链中运行任意SQL查询。

[source, javascript]
----
class UserSchema {
  up () {
    this.raw('SET sql_mode="TRADITIONAL"')
    .create('users', (table) => {
      table.increments()
    })
  }
}
----

==== db(closure)
`db`方法可以让您访问迁移中的 link:query-builder[数据库查询构建器]。如果要在更改数据库表时迁移数据，这将非常有用。

[source, javascript]
----
class UserSchema {
  up () {
    this.db(function * (database) {
      const names = yield database.from('users').pluck('name')
    })
  }
}
----

== Schema构建器
请参阅文档link:http://knexjs.org/#Schema-Building[Knex Schema Building, window="_blank"]，完全支持knex中的所有内容。以下是使用模式构建器创建*users*表的示例。

[source, javascript]
----
'use strict'

const Schema = use('Schema')

class UsersSchema extends Schema {
  up () {
    this.create('users', (table) => {
      table.increments()
      table.string('username').unique()
      table.string('email').unique()
      table.string('password', 60)
      table.timestamps()
      table.softDeletes()
    })
  }

  down () {
    this.drop('users')
  }
}

module.exports = UsersSchema
----
