---
permalink: database-hooks
categories:
- lucid
---
= Database Hooks

toc::[]

钩子是您在指定数据库操作之前或之后执行的操作。钩子为保证你的代码的DRY原则（代码复用）和易于理解起到关键作用。例如：在将用户密码保存带数据库之前将其进行*Hashing*加密

== 关于狗子

[pretty-list]
1. 钩子模型定义在 `app/Model/Hooks` 目录
2. 每个模型的钩子是一个ES2015（ES6）生成器方法，使得运行异步代码更简单
3. 你必须明确地在你的模型上定义钩子
4. 你可以像使用其他生成器命令一样使用`ace`命令来生成钩子
+
[source, bash]
----
./ace make:hook User

# or with predefined method
./ace make:hook User --method=encryptPassword
----
5. 钩子只能通过模型​​实例运行的命令执行，例如：调用静态`update`方法将不会执行钩子。
+
[source, javascript]
----
const user = yield User.find(1)
user.status = 'active'
// Will execute the update hooks
yield user.save()

// Will not execute the update hooks
yield User.query().where('id', 1).update('status', 'active')
----

== 基础例子
我们来看一下使用模型钩子加密用户密码的最基本的例子

.app/Model/Hooks/User.js
[source, javascript]
----
const Hash = use('Hash')
const User = exports = module.exports = {}

User.encryptPassword = function * (next) {
  this.password = yield Hash.make(this.password)
  yield next
}
----

接下来，我们需要手动在User模型上注册这个钩子

.app/Model/User.js
[source, javascript]
----
class User extends Lucid {

  static boot () { <1>
    super.boot()
    this.addHook('beforeCreate', 'User.encryptPassword') <2>
  }

}
----

<1> 所有钩子只能注册一次，`boot`方法是最佳的地方，因为Lucid可以保钩子只执行一次。
<2> 这种情况下，`addHook`方法将给定事件的钩子绑定到 `beforeCreate`(创建之前)执行

== 定义钩子
钩子是按照注册顺序执行的，要执行下一个钩子，你必须从现有的钩子中执行`yield next`，这个过程与HTTP中间件层非常相似。

==== addHook(event, [name], action)
该`addHook`方法将为指定事件定义一个钩子，或者，您可以给他一个唯一的名称，以后可以用于删除钩子。

[source, javascript]
----
static boot () {
  super.boot()
  this.addHook('beforeCreate', 'User.encryptPassword')
}
----

为钩子命名

[source, javascript]
----
static boot () {
  super.boot()
  this.addHook(
    'beforeCreate', <1>
    'encryptingPassword', <2>
    'User.encryptPassword' <3>
  )
}
----

<1> Hook event（钩子事件）
<2> Unique name（唯一的名字）
<3> 将执行的动作/操作。该操作可以是对简单的JavaScript方法的引用，也可以是由IOC容器解析的命名空间

==== defineHooks(event, arrayOfActions)
该`defineHooks`方法与`addHook`方法非常相似，使用`defineHooks`您可以一次定义多个钩子
 method is quite similar to the `addHook` method, instead you can define multiple hooks in one go.

[source, javascript]
----
class User extends Lucid {

  static boot () {
    super.boot()
    this.defineHooks('beforeCreate', ['UserHooks.validate', 'UserHook.encryptPassword'])
  }

}
----

==== removeHook(name)
像前面说的，您还可以在应用程序中随时删除命名的钩子。

[source, javascript]
----
User.removeHook('encryptingPassword')
----

== 终止数据库操作
钩子有能力通过抛出异常终止数据库操作

.app/Model/Hooks/User.js
[source, javascript]
----
UserHook.validate = function * (next) {
  if (!this.username) {
    throw new Error('Username is required')
  }
  yield next
}
----

== 钩子事件执行时间
以下是钩子事件的列表

[options="header"]
|====
| 事件 | 描述
| beforeCreate | 创建新纪录之前触发
| beforeUpdate | 更新已有记录之前触发
| beforeDelete | 删除指定记录之前触发
| beforeRestore | 该事件只有在启用link:lucid#_deletetimestamp[软删除]和恢复删除之前才会触发
| afterCreate | 创建新纪录之后触发
| afterUpdate | 更新已有记录记录后执行
| afterDelete | 删除成功已有记录后执行
| afterRestore | 软删除记录恢复后执行
|====
