---
permalink: sessions
categories:
- web-development-tools
---
= Sessions

toc::[]

AdonisJs具有开箱即用的支持，可将长期存储的Sessions保存到单个请求，仅限Sessions为*Flash Messages*。此外，您可以选择其中一个可用的驱动程序来保存Sessions数据。

NOTE: 为了保持会话cookie加密，请确保在*.env*文件中定义`APP_KEY`。或者，您可以使用`./ace key:generate`命令为您生成密钥。

== 驱动
以下是可用驱动程序的列表。

[support-list]
1. Cookie (cookie).
2. File (file).
3. Redis (redis).

NOTE: 在使用redis驱动程序之前，请确保设置link:redis[Redis provider]。

== 配置

看一下示例配置文件link:https://github.com/adonisjs/adonis-app/blob/develop/config/session.js[示例配置文件]。

[source, javascript]
----
const Env = use('Env')

module.exports = {
  // available options are file, cookie, redis
  driver: Env.get('SESSION_DRIVER', 'cookie'),
  // configuration settings for whichever driver you choose
  redis: Env.get('REDIS_URL', 'redis://localhost:6379'),
  cookie: 'adonis-session',
  file: {
    directory: 'sessions'
  }
  // other settings
  age: 120,
  clearWithBrowser: false,
  httpOnly: true,
  sameSite: true,
  domain: null,
  path: '/',
  secure: false,

}
----

== 基本例子
让我们来看一个从session中为给定用户saving/reading购物车项目的基本示例。

[source, javascript]
----
Route.get('carts', function * (request, response) {
  const cartItems = []
  yield request.session.put('cart-items', cartItems)
  yield response.send('Items added to cart successfully')
})
----

== 方法
以下是可用session方法的列表。

==== put(key, value)
向session存储添加一个值。

[source, javascript]
----
Route.post('users', function * (request, response) {
  yield request.session.put('username', 'doe')
  // or
  yield request.session.put({ username: 'doe' })
})
----

==== get(key, [defaultValue])
返回给定键的值。当实际值为`null`或`undefined`时，它将返回*defaultValue*。

[source, javascript]
----
Route.get('users/current', function * (request, response) {
  const username = yield request.session.get('username')
  // or
  const userId = yield request.session.get('userId', 123)
})
----

==== all
将所有会话值作为对象返回

[source, javascript]
----
const sessionValues = yield request.session.all()
----

==== forget(key)
删除给定键的值

[source, javascript]
----
yield request.session.forget('name')
----

==== pull(key, [defaultValue])
获取并删除给定键的值。将它视为调用外部参照xref:_get_key_defaultvalue[get]和xref:_forget_key[forget]在一起。

[source, javascript]
----
const username = yield request.session.pull('username')
----

== Flash消息
Flash消息用于为单个请求设置短暂的会话。当您希望使用表单错误和现有表单值重定向用户时，这将非常有用，因此无需重新键入所有内容，只能更正错误。

只需确保将`Flash`中间件添加到全局中间件列表中。

.app/Http/kernel.js
[source, javascript]
----
const globalMiddleware = [
  // ...
  'Adonis/Middleware/Flash'
  // ...
]
----

=== Flash消息的基本用法
让我们闪存表单提交验证错处理误的工作流，并查看我们如何在我们的视图中捕获它们。

.app/Http/routes.js
[source, javascript]
----
Route.on('users/create').render('users.create')
Route.post('users', 'UsersController.store')
----

.app/Http/Controllers/UsersController.js
[source, javascript]
----
'use strict'

class UsersController {

  * store (request, response) {
    const validation = yield Validator.validate(request.all(), rules)
    if (validation.fails()) {
      yield request
        .withAll() <1>
        .andWith({errors: validation.messages()}) <2>
        .flash()
      response.redirect('back')
    }
  }

}
----

<1> `withAll`方法将所有请求值添加到闪存会话存储。
<2> `andWith`方法是一个帮助程序来闪存自定义数据对象。这里我们用它来闪存验证错误。


.resources/views/users/create.njk
[source, twig]
----
{% for error in old('errors') %} <1>
    <li> {{ error.message }} </li>
{% endfor %}

{{ form.open({action: 'UsersController.store'}) }}

  {{ form.text('email', old('email')) }}
  {{ form.password('password', old('password')) }}

  {{ form.submit('Create Account') }}

{{ form.close() }}
----

<1> `old`方法用于从Flash消息中获取给定键的值。

=== Flash方法
以下是设置Flash消息的方法列表。

==== withAll
Will flash everything from `request.all()`.
会获取`request.all()`中闪存的一切

[source, javascript]
----
yield request.withAll().flash()
----

==== withOnly(keys...)
Flash值仅限于定义的键。

[source, javascript]
----
yield request.withOnly('email').flash()
----

==== withOut(keys...)
除了定义的键之外的所有Flash

[source, javascript]
----
yield request.withOut('password').flash()
----

==== with(values)
Flash自定义对象。

[source, javascript]
----
yield request.with({ error: 'Please fill in all details' }).flash()
----

==== andWith(values)
可自定义对象的方法发送请求数据。


[source, javascript]
----
yield request
  .withAll()
  .andWith({ error: 'Please fill in all details' })
  .flash()
----

=== 访问Flash值
您可以使用定义的助手访问视图内的Flash消息的值。 如果在所请求的密钥闪存中没有任何内容，它将显示defaultValue。


==== old(key, defaultValue)
[source, twig]
----
{{ old('username', user.username) }}
{# or #}
{{ old('profile.username') }}
----

==== flashMessages
[source, twig]
----
{% for key, message in flashMessages %}
  {{ message }}
{% endfor %}
----
