---
permalink: social-auth
categories:
- web-development-tools
---
= Social Auth Via Ally

toc::[]
Ally是adonisJs社会化认证提供商，它使得通过第三方网站（如Facebook，Twitter，Google等）对用户进行身份验证变得非常简单。

video::SDKz5qLMeBI[youtube, width=100%, height=480]

== Drivers（驱动）
以下是正式支持的驱动程序的列表，而您可以自由地贡献和添加更多适合您的驱动

[support-list]
* Facebook (facebook)
* Google (google)
* Twitter (twitter)
* Github (github)
* LinkedIn (linkedin)
* Instagram (instagram)
* Four Square (foursquare)

== 关于 Ally
[pretty-list]
1. Ally 是安装和支持社会化登录的第一步
2. 您需要在config/services.js文件中定义配置。配置包括 *Client Id*, *Secret* 和 *Redirect URI*.
3. Ally link:request[request]实例的对象ally，以便您可以访问控制器内的方法

== 创建
我们从设置过程开始，一如既往地非常简单。

.Installing From Npm
[source, bash]
----
npm i --save adonis-ally
----

.bootstrap/app.js
[source, javascript]
----
const providers = [
  // ...
  'adonis-ally/providers/AllyProvider'
  // ...
]
----

.app/Http/kernel.js
[source, javascript]
----
const globalMiddleware = [
  // ...
  'Adonis/Middleware/Ally'
  // ...
]
----
一旦设置过程成功完成，您就可以使用社交配置文件对用户进行身份验证。

== 配置
`config/services.js` 文件定义了ally的配置，您可以从link:https://raw.githubusercontent.com/adonisjs/adonis-ally/develop/examples/config.js[github]复制示例配置

.config/services.js
[source, javascript]
----
module.exports = {
  ally: {

    // Configuration for facebook
    facebook: {
      clientId: '',
      clientSecret: '',
      redirectUri: ''
    },

    // Configuration for github
    github: {
      clientId: '',
      clientSecret: '',
      redirectUri: ''
    }

  }
}
----

== 基础例子
我们先从Facebook的登录基础开始，我们将使用Facebook对用户进行身份验证，并创建他们的用户帐户而不用密码。

NOTE: 确保您已经定义了`config/services.js`文件中的facebook所需的配置

.Registering Routes
[source, javascript]
----
const Route = use('Route')

Route.get('facebook/login', 'LoginController.redirect')
Route.get('facebook/authenticated', 'LoginController.handleCallback')
----

.将用户重定向到提供者
首先，我们需要将用户重定向到Facebook，以允许我们的应用访问他们的个人资料。
[source, javascript]
----
class LoginController {

  * redirect (request, response) {
    yield request.ally.driver('facebook').redirect()
  }

}
----

.Handling Provider Callback
[source, javascript]
----
const User = use('App/Model/User')

class LoginController {

  * handleCallback (request, response) {
    const fbUser = yield request.ally.driver('facebook').getUser() <1>

    const searchAttr = {
      email: fbUser.getEmail()
    }

    const newUser = {
      email: fbUser.getEmail(),
      avatar: fbUser.getAvatar(),
      username: fbUser.getName()
    }

    const user = yield User.findOrCreate(searchAttr, newUser) <2>

    request.auth.loginViaId(user.id) <3>
  }

}
----

<1> 该`getUser`方法将获取给定提供者的用户配置文件。此方法仅在用户已重定向回时才有效`redirectUri`。
<2> `findOrCreate`是一种清晰的方法来查找具有用户详细信息的用户，或者如果找不到则创建新用户。
<3> 最后我们使用他们登录用户id。

== Ally 方法
以下是Ally提供商公开的可用方法的列表。

==== driver()
选择驱动

[source, javascript]
----
request.ally.driver('facebook')
----

==== redirect()
将用户重定向到提供商网站

[source, javascript]
----
yield request.ally.driver('facebook').redirect()
----

==== getRedirectUrl()
返回给定提供者的重定向网址

[source, javascript]
----
yield request.ally.driver('facebook').getRedirectUrl()
----

==== scope()
更新要用于请求许可的范围。

[source, javascript]
----
yield request.ally.driver('facebook')
  .scope(['public_profile', 'email', 'user_friends'])
  .redirect()
----

==== getUser()
返回给定提供者的用户配置文件

[source, javascript]
----
yield request.ally.driver('facebook').getUser()
----

==== fields()
在尝试访问用户配置文件时定义自定义字段

[source, javascript]
----
yield request.ally.driver('facebook')
  .fields(['email', 'verified']) <1>
  .getUser()
----

NOTE: 确保使用用户实例上的xref:_getoriginal[getOriginal] 法访问其他字段

== 用户方法
以下是用于获取用户配置文件详细信息的方法列表。所有这些方法都在xref:_getuser[getUser]返回的用户实例上调用。

==== getName()
[source, javascript]
----
const user = yield request.ally.driver('facebook').getUser()
user.getName()
----

==== getEmail()
[source, javascript]
----
const user = yield request.ally.driver('facebook').getUser()
user.getEmail()
----

==== getNickname()
[source, javascript]
----
const user = yield request.ally.driver('facebook').getUser()
user.getNickname()
----

==== getAvatar()
[source, javascript]
----
const user = yield request.ally.driver('facebook').getUser()
user.getAvatar()
----

==== getAccessToken()
[source, javascript]
----
const user = yield request.ally.driver('facebook').getUser()
user.getAccessToken()
----

==== getRefreshToken()
返回在访问令牌过期时要使用的刷新令牌。仅在使用OAuth2时才返回，并且提供商支持访问令牌到期。

[source, javascript]
----
const user = yield request.ally.driver('facebook').getUser()
user.getRefreshToken()
----

==== getExpires()
访问令牌到期时间（以毫秒为单位）。仅在使用OAuth2时才返回，并且提供商支持访问令牌到期。

[source, javascript]
----
const user = yield request.ally.driver('facebook').getUser()
user.getExpires()
----

==== getTokenSecret()
返回访问令牌秘密。仅在使用OAuth1时才返回。

TIP: Twitter是唯一使用OAuth1的驱动程序。

[source, javascript]
----
const user = request.ally.driver('twitter').getUser()
user.getTokenSecret()
----

==== getOriginal()
返回提供者的原始响应。

[source, javascript]
----
const user = request.ally.driver('twitter').getUser()
user.getOriginal()
----
