---
permalink: websocket
categories:
- web-development-tools
---
= WebSocket

toc::[]

WebSocket Provider使其在AdonisJs中构建实时应用程序变得非常简单。它配有开箱即用的认证，*渠道*和*房间*管理支持。

## 关于Ws Provider

[pretty-list]
1. 你应该定义接收传入的WebSocket连接的通道，同样在`app/Ws/socket.js`文件内部完成。
2. 所有传入的连接都可以使用中间件进行`auth`身份验证
3. 所有Web套接字操作都支持`ES2015`(ES6)生成器。例如：
+
[source, javascript]
----
Ws.channel('/chat', function (socket) {
  socket.on('message', function * (payload) {
  })
})
----
4. 您可以将控制器连接到您的频道，与路由相同。
+
[source, javascript]
----
Ws.channel('/chat', 'ChatController')
----

## 创建
NOTE: 如果您使用的是*3.2或更高版本*的adonisJs，你可以跳过这一步，因为此时Web Sockets已经预置

.Install via npm
[source, bash]
----
npm i --save adonis-websocket
----

接下来，我们需要在`bootstrap/app.js`文件中注册提供者和设置别名

.bootstrap/app.js
[source, javascript]
----
const providers = [
  'adonis-websocket/providers/WsProvider'
]

const aliases = {
  Ws: 'Adonis/Addons/Ws'
}
----

接下来，我们需要创建所需的目录和文件来组织我们的代码。
[source, bash]
----
mkdir -p app/Ws/Controllers
touch app/Ws/socket.js
touch app/Ws/kernel.js
----

1. 该`socket.js`文件用于定义websocket通道，您可以将其视为Http路由文件。
+
.app/Ws/socket.js
[source, javascript]
----
const Ws = use('Ws')

Ws.channel('/chat', function (socket) {
  // here you go
})
----
2. 该`kernel.js`文件用于定义全局和命名的中间件，就像您的Http中间件，但是用于Websocket连接
+
.app/Ws/kernel.js
[source, javascript]
----
const Ws = use('Ws')

const globalMiddleware = [
  'Adonis/Middleware/AuthInit'
]

const namedMiddleware = {
  auth: 'Adonis/Middleware/Auth'
}

Ws.global(globalMiddleware)
Ws.named(namedMiddleware)
----

最后，我们需要在引导Http服务器时加载`socket.js`和`kernel.js`文件，同样可以在`bootstrap/http.js`文件内部完成。

.bootstrap/http.js
[source, javascript]
----
use(Helpers.makeNameSpace('Ws', 'kernel'))
use(Helpers.makeNameSpace('Ws', 'socket'))
----

## 基本例子
请查看以下视频，显示如何在客户端和服务器之间交换消息。

video::rQTIwBV_ZgY[youtube, width=100%, height=480]

## Channels(频道)
通道可以更容易地在暴露Web套接字端点的情况下分发逻辑。对于每个通道，您可以遵循不同的身份验证过程或绑定不同的中间件。

TIP: Adonisjs利用*多路复用*而不是为每个通道创建不同的连接。


.app/Ws/socket.js
[source, javascript]
----
'use strict'

const Ws = use('Ws')

Ws.channel('chat', function (socket, request, presence) {
  socket.on('news', function (message) {

  })
})
----

每次新插座加入聊天频道并接收以下内容时，上述关闭将被执行。

socket:: 用户套接字实例发出和收听事件
request:: 握手时实例link:request[request]
presence::一个特殊的`presence`来跟踪套接字。阅读更多关于xref:_presence[presence].

## Controllers
除了关闭之外，您还可以将控制器绑定到通道。所有控制器都存储在`app/Ws/Controllers`目录中，可以与Route控制器相同。

[source, javascript]
----
Ws.channel('chat', 'ChatController')
----

现在控制器可以通过创建适当的方法来侦听新的事件

.app/Ws/Controllers/ChatController.js
[source, javascript]
----
'use strict'

class ChatController {

  constructor (socket) {
    this.socket = socket
  }

  onMessage (message) {
    // listening for message event
  }

}
----

`onMessage`每次从客户端触发消息事件时，将调用该方法。此外，您可以使侦听器成为执行异步操作的生成器方法。

[source, javascript]
----
onMessage (message) {

}

// CAN BE

* onMessage (message) {
  const savedMessage = yield Message.create({ body: message })
}
----

所有事件的听众必须从事件名称开始，`on`并*camel case*。例如，new:user将onNewUser在控制器上调用方法。

[options="header"]
|====
| Event Name | Controller Method
| message | onMessage
| new:user | onNewUser
| user:left| onUserLeft
|====

## Rooms(房间)
`Rooms`使建立多房间聊天系统变得更加容易。例如，Slack有公共房间，任何人都可以加入和离开，而私人房间需要进一步的授权。

以同样的方式，AdonisJs可以让您勾选一个套接字，然后才能收听房间内的事件。

### Joining A Room
该`joinRoom`信道控制器上方法每一个插座试图加入室温时将自动调用。您可以使用此方法来授权联合操作或通过抛出异常来拒绝它。

#### Server
.app/Ws/socket.js
[source, javascript]
----
const Ws = use('Ws')

Ws
.channel('chat', 'ChatController')
.middleware('auth')
----

.app/Ws/Controllers/ChatController.js
[source, javascript]
----
'use strict'

class ChatController {
  constructor (socket) {
    this.socket = socket
  }

  * joinRoom (room) {
    const user = this.socket.currentUser
    // throw error to deny a socket from joining room
  }
}
----

#### Client
[source, javascript]
----
const io = ws('')
const client = io.channel('chat').connect()

client.joinRoom('lobby', {}, function (error, joined) {
  // status
})
----

### 发送消息到一个房间
一旦套接字加入了一个房间，它就可以收听消息。

#### Server
[source, javascript]
----
this.socket.inRoom('lobby').emit('message', 'Hello world')
----

#### Client
[source, javascript]
----
client.on('message', function (room, message) {
})
----

### 离开一个房间
为了离开房间，客户可以调用`leaveRoom`方法。

#### Server

.app/Ws/Controllers/ChatController.js
[source, javascript]
----
'use strict'

class ChatController {
  constructor (socket) {
    this.socket = socket
  }

  * leaveRoom (room) {
    // Do cleanup if required
  }

  * joinRoom (room) {
    const user = this.socket.currentUser
    // throw error to deny a socket from joining room
  }
}
----

#### Client
[source, javascript]
----
const io = ws('')
const client = io.channel('chat').connect()
client.leaveRoom('lobby', {}, function (error, left) {
  // status
})
----

## 存在
存在功能允许您跟踪给定用户的套接字。显示在线用户列表和他们在线的设备数量是有帮助的。此外，当用户注销时，您可以断开所有相关的套接字，以确保他们没有收到任何实时消息。

查看此视频以了解深度的存在。

video::p_QNEZdQt6Y[youtube, width=100%, height=480]

## 存在方法
以下是存在方法的列表

### track(socket, userId, [meta])
该track方法允许您使用其userId跟踪给定用户的套接字。或者，您也可以传递元数据。

[source, javascript]
----
class ChatController {

  constructor (socket, request, presence) {
    presence.track(socket, socket.currentUser.id, {
      device: 'chrome'
    })
  }

}
----

### pull(userId, callback)
从给定用户的在线列表中提取套接字列表。拉动的插座将不再被跟踪。

[source, javascript]
----
const Ws = use('Ws')
const chatChannel = Ws.channel('chat')
const chromeOnlySockets = chatChannel.presence.pull(userId, function (payload) {
  return payload.meta.device === 'chrome'
})

// disconnect user sockets from chrome
chromeOnlySockets.forEach((payload) => {
  payload.socket.disconnect()
})
----

## 套接字方法
以下是可以从套接字实例调用的方法列表。

#### on(event, callback)
监听一个事件

[source, javascript]
----
socket.on('greet', function (greeting) {

})
----

#### once(event, callback)
只听一次事件

[source, javascript]
----
socket.once('greet', function (greeting) {

})
----

#### emit(event, ...properties)
发出一个事件
[source, javascript]
----
socket.emit('greet', 'Hello world')
----

#### toEveryone()
向每个人发出消息，包括始发套接字本身。

[source, javascript]
----
socket.toEveryone().emit('greet', 'Hello world')
----

#### toMe()
仅向原始`socket`发出消息。
[source, javascript]
----
socket.toMe().emit('greet', 'Hello world')
----

#### exceptMe()
向除了发出该消息以外的所有人发出消息。

[source, javascript]
----
socket.exceptMe().emit('user:join', 'User joined!')
----

#### to(ids)
仅向特定的套接字ID发出消息
[source, javascript]
----
socket.to([]).emit('greet', 'Hello world')
----

#### inRoom(room)
在给定的房间发出消息。
[source, javascript]
----
socket.inRoom('lobby').emit('greet', 'Hello world')
----

#### inRooms(rooms)
向多个房间发出消息。
[source, javascript]
----
socket.inRoom(['lobby', 'watercooler']).emit('greet', 'Hello world')
----

#### disconnect
断开套接字接收/发送消息。
[source, javascript]
----
socket.disconnect()
----

## 渠道方法
下面是可以在通道实例上使用的方法列表

#### middleware(...middleware)
在给定的频道上应用一组中间件。确保在`app/Ws/kernel.js`文件中定义中间件。

[source, javascript]
----
Ws
  .channel('chat')
  .middleware('auth')

// OR

Ws
  .channel('chat')
  .middleware('auth:jwt')
----

#### emit(event, ...properties)
向所有已连接上的`sockets`发送消息

[source, javascript]
----
const chatChannel = Ws.channel('chat')
chatChannel.emit('message', 'Hello world')
----

#### inRoom(room)
在给定的房间发出消息
[source, javascript]
----
const chatChannel = Ws.channel('chat')
chatChannel.inRoom('lobby').emit('message', 'Hello world')
----

#### inRooms(rooms)
向所有给定的房间发出消息
[source, javascript]
----
const chatChannel = Ws.channel('chat')
chatChannel.inRooms(['lobby', 'watercooler']).emit('message', 'Hello world')
----

#### to(ids)
仅向特定的套接字ID发出消息
[source, javascript]
----
const chatChannel = Ws.channel('chat')
chatChannel.to([]).emit('greet', 'Hello world')
----

#### get(socketId)
使用套接字标识获取套接字实例

[source, javascript]
----
const chatChannel = Ws.channel('chat')
const socket = chatChannel.get(socketId)
----

## WebSocket客户端
可以使用npm安装基于浏览器的web*Common js*客户端模块，或者使用bower安装*ADM*模块
，也可以从cnd上引用它。
The client library to be used with browser-based web apps can be installed as *Common Js* module from link:https://npmjs.org/package/adonis-websocket-client[npm, window="_blank"], *AMD* module from bower or you can reference it from a link:https://unpkg.com/adonis-websocket-client/dist/ws.min.js[CDN, window="_blank"].

### CommonJs用法
安装后，您可以像任何其他npm模块一样要求模块。

[source, bash]
----
npm i --save adonis-websocket-client
----

[source, javascript]
----
const ws = require('adonis-websocket-client')
const io = ws('http://localhost:3333', {})
----

### AMD 用法
首先，从bower安装包

[source, bash]
----
bower i --save adonis-websocket-client
----

[source, javascript]
----
requirejs(['adonis-websocket-client'], function (ws) {
  const io = ws('http://localhost:3333', {})
})
----


### CDN用法
CDN脚本文件将创建一个全局`ws`。

[source, html]
----
<script src="https://unpkg.com/adonis-websocket-client/dist/ws.min.js"></script>
<script>
  const io = ws('http://localhost:3333', {})
</script>
----

## 客户渠道方式
以下是使用客户端SDK调用的方法列表

#### connect(callback)
连接到给定的频道

[source, javascript]
----
const client = io.channel('chat')
client.connect(function (error, connected) {
  if (error) {
    // do something
    return
  }
  // all good
})
----

#### emit(event, ...properties)
发出一个事件

[source, javascript]
----
client.emit('message', 'Hello world')
----

#### on(event, callback)
监听一个事件

[source, javascript]
----
client.on('message', function (message) {
})
----

#### once(event, callback)
只监听事件一次

[source, javascript]
----
client.once('message', function (message) {
})
----

#### joinRoom(room, payload, callback)
通知服务器加入房间并发送可选数据对象作为*payload*.

[source, javascript]
----
client.joinRoom('lobby', {}, function (error, joined) {
})
----

#### leaveRoom(room, payload, callback)
离开房间

[source, javascript]
----
client.leaveRoom('lobby', {}, function (error, left) {
})
----

#### withBasicAuth(username, password)
通过传递用于基本认证的用户名和密码来连接到频道

[source, javascript]
----
client
  .withBasicAuth('foo', 'secret')
  .connect(function () {
  })
----

#### withJwt(token)
通过传递JWT令牌进行认证，以连接到该通道

[source, javascript]
----
client
  .withJwt('token')
  .connect(function () {
  })
----

#### withApiKey(token)
通过传递个人API令牌进行身份验证，以连接到频道

[source, javascript]
----
client
  .withApiKey('personal_token')
  .connect(function () {
  })
----
